export const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/product-1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      countInStock: 3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/product-2.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 3,
    },
    {
      _id: "3",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/product-3.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
    },
    {
      _id: "4",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/product-4.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 2,
    },
    {
      _id: "5",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/product-5.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 1,
    },
    {
      _id: "6",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/product-6.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
    },
  ],
};
